### ISSUE TITLE
Опечатки в документации

### ISSUE THREAD

**Issue by uh-zuh** [ydb-platform/ydb#105]
Пока читал собрал разные опечатки в документации или непонятные места, которые выглядят как опечатки.

1) https://ydb.tech/ru/docs/concepts/cluster/common_scheme_ydb
> Лог таблетки устроен в списка блобов

Ничего не понятно.

2) https://ydb.tech/ru/docs/concepts/cluster/distributed_storage
> которое имеет взаимодействия

Что-то непонятное.

3) https://ydb.tech/ru/docs/best_practices/pk_scalability
> что в приведет к равномерной нагрузке на систему

Лишняя "в" или должно было быть "в итоге".

4) https://ydb.tech/ru/docs/best_practices/secondary_indexes
> Транзакционные системы применяет индексы

применяЮт?

5) https://ydb.tech/ru/docs/best_practices/secondary_indexes
> field1 = $f1, field2 = $f2

Тут и должно быть в результате два Bool значения или хотелось написать $f1 AS field1?

6) https://ydb.tech/ru/docs/best_practices/secondary_indexes
> SELECT series_id,

Лишняя запятая?

7) https://ydb.tech/ru/docs/best_practices/batch_upload
> В случае успешного ответа запрос, метод BulkUpsert

"на" запрос?

8) https://ydb.tech/ru/docs/yql/reference/types/optional
> lookup

Ссылка на несуществующую страницу https://ydb.tech/en/docs/s_expressions/functions#lookup

9) https://ydb.tech/ru/docs/yql/reference/syntax/lexer
> Имя SQL хинта является должно состоять

"является" лишнее?

**Comment by zinal** [comment]
Спасибо, буду исправлять (YCDOCS-6448).
