### ISSUE TITLE
Разобраться, почему TPC-H 1000 q09 проходит в main, но не проходит в stable

### ISSUE THREAD

**Issue by iddqdex** [ydb-platform/ydb#10567]
Имеем таймауты.
Отчеты с планами:
[stable-24-3-10-analytics](https://nda.ya.ru/t/Ea8PRxTT78zDA8)
[main](https://nda.ya.ru/t/7w7qzxb578zDCp)

**Comment by Hor911** [comment]
#10636

**Comment by Hor911** [comment]
#10637

**Comment by iddqdex** [comment]
Проблема в конфигурации памяти на кластерах. Добавил конфиг resource_broker и memory_controller и проблема ушла.
