### ISSUE TITLE
Разобраться, почему TPC-DS 100 q04 проходит в main, но не проходит в stable

### ISSUE THREAD

**Issue by iddqdex** [ydb-platform/ydb#10568]
Mkqp memory limit.
Воспроизводится в `stable-24-3-8-analytics`, но **НЕ воспроизводится** в `main` и `stable-24-3-10-analytics`.
Отчеты с планами:
[stable-24-3-8-analytics](https://nda.ya.ru/t/O1WU1-fC78zDYM)
[stable-24-3-10-analytics](https://nda.ya.ru/t/Uymjk_L378zDeG)
[main](https://nda.ya.ru/t/_UGS5-Do78zDak)

**Comment by Hor911** [comment]
24-3-8 does not contains MapJoin pessimization yet

**Comment by iddqdex** [comment]
Проблема в конфигурации памяти на кластерах. Добавил конфиг resource_broker и memory_controller и проблема ушла.
