### ISSUE TITLE
Fix --import-data  description in ydb tools restore -help

### ISSUE THREAD

**Issue by s-sabitova** [ydb-platform/ydb#10572]
Current description states the following

```
ydb tools restore -help

<...>
--import-data   Use ImportData - a more efficient way to upload data with lower consistency level. Global secondary
                           indexes are not supported in this mode.
                           Default: 0.
```

In fact, it's possible to restore secondary indexes with this option enabled. The only case this wouldn't work is when the table and its indexes already exist. If the table is not present, the import job will successfully restore the table and the indexes.

The description in -help should be changed accordingly.

**Comment by CyberROFL** [comment]
An incorrect description has been added here: https://github.com/ydb-platform/ydb/pull/436
