### ISSUE TITLE
TPCC: Regression in main on 16k wh

### ISSUE THREAD

**Issue by naspirato** [ydb-platform/ydb#10570]
https://datalens.yandex/wf5xdbbl923ok?tab=qrg&state=a060a97a500

| Monitoring Link | Branch | Environment | Timestamp (Test Run Start) | Commit SHA | Timestamp (Commit) | Transactions/sec | Throughput (ops/sec) | Throughput (%) | Latency (ms) |
|---|---|---|---|---|---|---|---|---|---|
 | origin/main | default | 15.10.2024 23:06:29 | [b390c9db](https://github.com/ydb-platform/ydb/commit/b390c9dba1929b46726243ab260df05f48f1fd06) | 15.10.2024 18:24:48 | 16,000 | **203,701** | 99.00 | 256 |
 | origin/main | default | 15.10.2024 16:35:11 | [168df93b](https://github.com/ydb-platform/ydb/commit/168df93b6c26268418beec08fb05c7951972c7d1) | 15.10.2024 14:15:53 | 16,000 | **202,852** | 98.59 | 416 |
 | origin/main | default | 15.10.2024 09:52:55 | [11f9117b](https://github.com/ydb-platform/ydb/commit/11f9117b55ff8fa16284776448d3a9463c83b8c7) | 15.10.2024 07:57:34 | 16,000 | **203,371** | 98.84 | 288 |
| origin/main | default | 14.10.2024 20:35:26 | [942b770d](https://github.com/ydb-platform/ydb/commit/942b770d3fef2f8df0311740e08eef1ffe40cd11) | 14.10.2024 16:53:57 | 16,000 | 204,509 | 99.39 | 224 |
 | origin/main | default | 14.10.2024 13:47:30 | [b4ac18d0](https://github.com/ydb-platform/ydb/commit/b4ac18d0eb2195aba894f5a302d2dd474482a8fa) | 14.10.2024 12:05:43 | 16,000 | 204,347 | 99.31 | 224 |
 | origin/main | default | 14.10.2024 06:59:31 | [ddea4fb3](https://github.com/ydb-platform/ydb/commit/ddea4fb3a1b02553c253b51078529f48d136dee8) | 14.10.2024 05:27:38 | 16,000 | 204,426 | 99.35 | 224 |

git log --graph --oneline --pretty=format:'%H - %ad %s' 942b770d3fef2f8df0311740e08eef1ffe40cd11\^..11f9117b55ff8fa16284776448d3a9463c83b8c7

* 11f9117b55ff8fa16284776448d3a9463c83b8c7 - Tue Oct 15 09:57:34 2024 \+0200 PDisk noop scheduler (#9332)
* 6bd8708c3ff1e954938c317aa7ad9fbf0a58e6ea - Tue Oct 15 10:38:08 2024 \+0300 Small speedup tpcds generator (#10424)
* d14474ede3768ff3a535f83ca26b4cbc2533f73d - Tue Oct 15 10:37:58 2024 \+0300 Fix tpch generator (#10423)
* fad06665db042a44df61d6952efb35561c5c027a - Tue Oct 15 10:26:27 2024 \+0300 redefine json_errdetail (#10420)
* 29998254ecfcc60888f91669dbcd74fe23f1af3d - Tue Oct 15 08:43:27 2024 \+0200 \[refactoring\] Do not include actorsystem.h into actor.h (#10394)
* 5d0627c077beaf3fc9c615b36b8f33a7e6cedfe8 - Tue Oct 15 09:21:30 2024 \+0300 YQ-3753 Fix build (#10421)
* a0078aafab845708279ceb7e1a55babd067146d1 - Tue Oct 15 08:47:40 2024 \+0300 YQ-3753 Shared reading: metadatafields (#10370)
* 5a2bffd28adc0a1d0a306f16ec334b45f7a07db8 - Tue Oct 15 07:21:18 2024 \+0300 refactoring tpch generator (#10414)
* df7e5a09728d065cde2fb39264bbcafbda0cdc96 - Tue Oct 15 03:04:18 2024 \+0300 Add hint for compact Join (#10236)
* 6e67eb55d9298cc720d06c15483498dc24df7c6a - Mon Oct 14 22:10:27 2024 \+0300 Yq 3724 Move no_pg_wrapper to fq (#10360)
* 942b770d3fef2f8df0311740e08eef1ffe40cd11 - Mon Oct 14 18:53:57 2024 \+0200 ci: add antlr4 to github runner image (#10407)

**Comment by naspirato** [comment]
### Без волатильных транзацкий - 4,5%
### Performance Comparison: default_volatile_off

| Monitoring Link | Branch | Environment | Timestamp (Test Run Start) | Commit SHA | Timestamp (Commit) | Transactions/sec | Throughput (ops/sec) | Throughput (%) | Latency (ms) |
|---|---|---|---|---|---|---|---|---|---|
| [perf4](https://monitoring.yandex-team.ru/projects/kikimr/dashboards/monllvavev47fqmirf72?p.cluster=ydb_qa_01_klg_perf4&p.host=cluster&p.slot=static&p.database=%2FRoot%2Fdb1&from=1729162341000&to=1729169571000&forceRefresh=1703166697252&refresh=off) | origin/main | default_volatile_off | 17.10.2024 10:52:51 | [11f9117b](https://github.com/ydb-platform/ydb/commit/11f9117b55ff8fa16284776448d3a9463c83b8c7) | 15.10.2024 07:57:34 | 16,000 | 178,946 | 86.97 | 5,500 |
| [perf4](https://monitoring.yandex-team.ru/projects/kikimr/dashboards/monllvavev47fqmirf72?p.cluster=ydb_qa_01_klg_perf4&p.host=cluster&p.slot=static&p.database=%2FRoot%2Fdb1&from=1729129223000&to=1729136453000&forceRefresh=1703166697252&refresh=off) | origin/main | default_volatile_off | 17.10.2024 01:40:53 | [942b770d](https://github.com/ydb-platform/ydb/commit/942b770d3fef2f8df0311740e08eef1ffe40cd11) | 14.10.2024 16:53:57 | 16,000 | 187,939 | 91.34 | 4,250 |

**Comment by naspirato** [comment]
Regression starts in commit https://github.com/ydb-platform/ydb/commit/11f9117b55ff8fa16284776448d3a9463c83b8c7

**Comment by va-kuznecov** [comment]
possibly fix - https://github.com/ydb-platform/ydb/pull/10565

**Comment by naspirato** [comment]
@va-kuznecov 
still same results

 origin/main | default_volatile_off | 18.10.2024 01:44:10 | e8cfb021 | 17.10.2024 19:39:03 | 16 000 | 179 625 | 87,30 | 5 500
| -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by va-kuznecov** [comment]
revert all noop scheduler related commits - https://github.com/ydb-platform/ydb/pull/10600
