### ISSUE TITLE
BlockShuffle optimization

### ISSUE THREAD

**Issue by lll-phill-lll** [ydb-platform/ydb#10653]
@Hor911  обратил внимание, что при нарезке блоков перед отправкой выделятся много памяти: outputBlocksNum * max(outputBlocks.size()). Поэтому он предлагает улучшить это место:

# О коде

Тут происходит разделение входного блока на блоки:

https://github.com/ydb-platform/ydb/blob/7bd8eb1c09ac3ff1fe2cd833b5f0e12cbc10a12c/ydb/library/yql/dq/runtime/dq_output_consumer.cpp#L391

Тут дальше выбирается размер аллокации для получившихся блоков:

https://github.com/ydb-platform/ydb/blob/7bd8eb1c09ac3ff1fe2cd833b5f0e12cbc10a12c/ydb/library/yql/dq/runtime/dq_output_consumer.cpp#L396

# О проблеме

Предполагается, что из-за этого может выделяться и отправляться память, которая никем не используется.

Предлагается улучшить выделение памяти в этом месте и не выделять много лишнего.

Плохой, но по идее рабочий вариант решения - пересоздавать MakeBuilders под каждый блок отдельно:
https://github.com/ydb-platform/ydb/blob/7bd8eb1c09ac3ff1fe2cd833b5f0e12cbc10a12c/ydb/library/yql/dq/runtime/dq_output_consumer.cpp#L400

Также можно попробовать вместо Max брать какое-то другое значение, например, среднее. Тогда в случае блоков, чей размер получится больше среднего, отправлять 2 блока.

**Comment by Hor911** [comment]
Проверил "наивный вариант"
- потребление памяти уменьшается, хорошо заметно на TPC-H Q3 scale 1000/10000, до 10% AnonRss
- значимой деградации по производительности не видно
