### ISSUE TITLE
KqpSystemView.PartitionStatsFollower is flaky under ASAN

### ISSUE THREAD

**Issue by jepett0** [ydb-platform/ydb#10846]
An example of the failure:
- https://nebius.testmo.net/automation/runs/results/73095?group_by=automation_run_tests:status_id&group_id=3&test_id=1226553975

You can see in the context that it fails about 10% of the time with the same error:
```
Test crashed (return code: -6)
```

**Comment by azevaykin** [comment]
https://github.com/ydb-platform/ydb/blob/95e4ddfda302e1dbdbda906da50cb3c23b6d8d0a/ydb/core/sys_view/partition_stats/partition_stats.cpp#L701
