### ISSUE TITLE
[question] How to create one more database using local docker deployment?

### ISSUE THREAD

**Issue by fortunado** [ydb-platform/ydb#1085]
How to create one more database using local docker deployment? Is it possible?

Thanks.

**Comment by blinkov** [comment]
Hi @fortunado, what kind of usecase do you have in mind? I guess you could achieve this by crafting a custom docker image with custom configuration, but afaik there's no guide on how to do that.

Also, have you considered just running multiple containers, one per database?

**Comment by fortunado** [comment]
I've just started to play with YDB, and my goal for now very simple - have running single YDB server with multiple databases (does not matter will it be docker or local install).

Now wondering is it possible to get the same result as with Postgres container (there i can create multiple databases and users just using CREATE DATABASE + CREATE ROLE in single container). 

And as I didn't find any information about CREATE DATABASE command, I've supposed that this is some hidden system level and may be on-premise deployment limitation.

If somebody know where is YDB offical Dockerfile located (if one is opensourced), please, share.

What I've found at the moment is ansible playbook that have create database task - will dig deeper into it (https://github.com/ydb-platform/ydb-ansible).

**Comment by fortunado** [comment]
Found solution for my question:
1) go to inside YDB container, something like this `docker exec --it <YDB-CONTAINER-ID> /bin/bash`
2) `cat /root/ydb_data/kikimr_configs/config.yaml` - find as mentioned in the manual https://ydb.tech/docs/en/deploy/manual/deploy-ydb-on-premises#create-db the hint about where to find storage pool info:
> Name of the storage pool and the number of storage groups allocated. The pool name usually means the type of data storage devices and must match the `storage_pool_types.kind` setting inside the `domains_config.domain` element of the configuration file" 
3) keep in mind that `'/local'` database - is the root domain of the ydb installation inside docker, so all other databases must be under root
4) and finally run for create new `db1` and `db2` under `/local` root domain:
```bash
root@ydb:/# ./ydbd -s "grpc://localhost:2136" admin db /local/db2 create --no-tx hdd:1
OK
root@ydb:/# ./ydbd -s "grpc://localhost:2136" admin db /local/db3 create --no-tx hdd1:1
OK
```
