### ISSUE TITLE
Mute ydb/core/statistics/aggregator/ut/AnalyzeColumnshard.AnalyzeStatus

### ISSUE THREAD

**Issue by naspirato** [ydb-platform/ydb#10870]
Mute:
ydb/core/statistics/aggregator/ut/AnalyzeColumnshard.AnalyzeStatus

Branch:
main

**Add line to [muted_ya.txt](https://github.com/ydb-platform/ydb/blob/main/.github/config/muted_ya.txt):**
```
ydb/core/statistics/aggregator/ut AnalyzeColumnshard.AnalyzeStatus
```

Owner: TEAM:@ydb-platform/datashard

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**

**Summary history:** 
 AnalyzeColumnshard.AnalyzeStatus: Flaky last 4 days. Today: success_rate 91%, Pass:42 Fail:4 Mute:0 Skip:0

**Test run history:** [link](https://datalens.yandex/34xnbsom67hcq?full_name=__in_ydb%2Fcore%2Fstatistics%2Faggregator%2Fut%2FAnalyzeColumnshard.AnalyzeStatus)

More info in [dashboard](https://datalens.yandex/4un3zdm0zcnyr)

**Comment by azevaykin** [comment]
https://github.com/ydb-platform/ydb/pull/10815
