### ISSUE TITLE
If single BulkUpsert contains several records with the same primary key then CS write result is undetermined

### ISSUE THREAD

**Issue by SloNN** [ydb-platform/ydb#11380]
Say we have several records with the same primary key in single batch

```
key=1 a=1
key=1 a=2
key=1 a=3
```

If we write the batch to the column shards then resulting record is unknown, it may be any of
```
key=1 a=1
```
```
key=1 a=2
```
```
key=1 a=3
```

Instead there should be guarantee that only last record for the key is written to column shards, `a=3` in our case

**Comment by zverevgeny** [comment]
dup: https://github.com/ydb-platform/ydb/issues/11915
