### ISSUE TITLE
Mute ydb/core/kqp/ut/service/KqpQueryService.Ddl_Dml

### ISSUE THREAD

**Issue by kunga** [ydb-platform/ydb#11521]
ydb/core/kqp/ut/service/KqpQueryService.Ddl_Dml

**Add line to [muted_ya.txt](https://github.com/ydb-platform/ydb/blob/main/.github/config/muted_ya.txt):**
`ydb/core/kqp/ut/service KqpQueryService.Ddl_Dml`

 Owner: [TEAM:@ydb-platform/qp](https://github.com/orgs/ydb-platform/teams/qp)

**Read more in [mute_rules.md](https://github.com/ydb-platform/ydb/blob/main/.github/config/mute_rules.md)**  

**Summary history:**
 Success rate **20%**
Pass:1 Fail:4 

**Test run history:** [link](https://datalens.yandex/34xnbsom67hcq?full_name=ydb/core/kqp/ut/service/KqpQueryService.Ddl_Dml)

More info in [dashboard](https://datalens.yandex/4un3zdm0zcnyr)

**Comment by CyberROFL** [comment]
Reverted: https://github.com/ydb-platform/ydb/pull/11515
