### ISSUE TITLE
Column "Column" is not in source column set. Did you mean "ColumnaAlias"?

### ISSUE THREAD

**Issue by dimajolkin** [ydb-platform/ydb#122]
**ORDER BY** не сортирует по название колонки по колоке если у неё определен алиас

Не уверен баг это или фича в доках про это не указано, у меня проблемка с сортировкой:
`select sort as sort2 from teacher order by sort desc;  
-- колоке sort добавлен алиас sort2 а в сортировке оригинальное название` 
это запрос postgres выполнит нормально при этом YDB сообщает
`Column sort is not in source column set. Did you mean sort2?`

Это баг или фича? если фича то ок с этим можно жить(

**Comment by spuchin** [comment]
SORT logically is performed after projection, so it can reference only "renamed" columns.
