### ISSUE TITLE
Missing link on landing page

### ISSUE THREAD

**Issue by mishankov** [ydb-platform/ydb#12214]
Link in "How to get started?" section of landing page (https://ydb.tech/) leads to 404
![image](https://github.com/user-attachments/assets/538e1cfa-244d-460e-953d-3580023a08c3)

Link - https://ydb.tech/docs/en/getting_started/self_hosted/ydb_docker

**Comment by anton-bobkov** [comment]
Thank you for submitting the issue. It has been fixed.
