### ISSUE TITLE
[viewer/nodes]: no disconnect time for disconnected node

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb#12358]
For disconnected node `DisconnectTime` field is expected, but we receive only `NodeId` and `Host` fields in response

<img width="585" alt="Screenshot 2024-12-06 at 13 29 08" src="https://github.com/user-attachments/assets/e738c505-13a9-49ac-aa1c-77a45068d2f4">

**Comment by adameat** [comment]
> For disconnected node `DisconnectTime` field is expected, but we receive only `NodeId` and `Host` fields in response
> 
@artemmufazalov  have you included filed "DisconnectTime" in the fields_required?

**Comment by artemmufazalov** [comment]
> @artemmufazalov have you included filed "DisconnectTime" in the fields_required?

@adameat yes, it's present if DisconnectTime is included, thank you

<img width="515" alt="Screenshot 2024-12-09 at 11 16 16" src="https://github.com/user-attachments/assets/cf67e40e-53f9-4c87-8f6f-f7540688bc2d">
