### ISSUE TITLE
kqprun freezes on select count(*)

### ISSUE THREAD

**Issue by lll-phill-lll** [ydb-platform/ydb#12518]
Kqprun freezes on a simple select count(*) query. Meanwhile thee is no such issue on dqrun (testes scales 1 and 100).

# How to reproduce

HEAD:  e838a620433

## Run command:

./kqprun -s s1.sql -p queries/select.sql -C query

## queries/select.sql: 

select count(*) from lineitem;

## s1.sql:

CREATE EXTERNAL DATA SOURCE tpc WITH (
    SOURCE_TYPE="ObjectStorage",
    LOCATION="file:///extra_kek/tpc/",
    AUTH_METHOD="NONE"
);

CREATE EXTERNAL TABLE customer (
    c_acctbal Double NOT NULL,
    c_mktsegment String NOT NULL,
    c_phone String NOT NULL,
    c_nationkey Int32 NOT NULL,
    c_custkey Int32 NOT NULL,
    c_name String NOT NULL,
    c_comment String NOT NULL,
    c_address String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/customer/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE lineitem (
    l_orderkey Int64 NOT NULL,
    l_partkey Int32 NOT NULL,
    l_suppkey Int32 NOT NULL,
    l_linenumber Int32 NOT NULL,
    l_quantity Double NOT NULL,
    l_extendedprice Double NOT NULL,
    l_discount Double NOT NULL,
    l_tax Double NOT NULL,
    l_returnflag String NOT NULL,
    l_linestatus String NOT NULL,
    l_shipdate Date NOT NULL,
    l_commitdate Date NOT NULL,
    l_receiptdate Date NOT NULL,
    l_shipinstruct String NOT NULL,
    l_shipmode String NOT NULL,
    l_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/lineitem/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE nation (
    n_nationkey Int32 NOT NULL,
    n_name String NOT NULL,
    n_regionkey Int32 NOT NULL,
    n_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/nation/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE orders (
    o_orderkey Int64 NOT NULL,
    o_custkey Int32 NOT NULL,
    o_orderstatus String NOT NULL,
    o_totalprice Double NOT NULL,
    o_orderdate Date NOT NULL,
    o_orderpriority String NOT NULL,
    o_clerk String NOT NULL,
    o_shippriority Int32 NOT NULL,
    o_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/orders/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE part (
    p_partkey Int32 NOT NULL,
    p_name String NOT NULL,
    p_mfgr String NOT NULL,
    p_brand String NOT NULL,
    p_type String NOT NULL,
    p_size Int32 NOT NULL,
    p_container String NOT NULL,
    p_retailprice Double NOT NULL,
    p_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/part/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE partsupp (
    ps_partkey Int32 NOT NULL,
    ps_suppkey Int32 NOT NULL,
    ps_availqty Int32 NOT NULL,
    ps_supplycost Double NOT NULL,
    ps_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/partsupp/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE region (
    r_regionkey Int32 NOT NULL,
    r_name String NOT NULL,
    r_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/region/",
    FORMAT="parquet"
);

CREATE EXTERNAL TABLE supplier (
    s_suppkey Int32 NOT NULL,
    s_name String NOT NULL,
    s_address String NOT NULL,
    s_nationkey Int32 NOT NULL,
    s_phone String NOT NULL,
    s_acctbal Double NOT NULL,
    s_comment String NOT NULL
) WITH (
    DATA_SOURCE="tpc",
    LOCATION="/h/1/supplier/",
    FORMAT="parquet"
);

## Result:

➜  kqprun git:(main) ✗ ./kqprun -s s1.sql -p queries/select.sql -C query
2024-12-11T16:44:28.794355+03:00 Initialization of kqp runner...
2024-12-11T16:44:30.143243+03:00 Executing scheme query...
2024-12-11T16:44:32.146781+03:00 Executing script...

Generic request finished. Total duration: 1800.000326s
Failed to execute query, reason:
Request finished with status: TIMEOUT
Issues:
<main>: Error: Request timeout 1800000ms exceeded
<main>: Error: Cancelling after 1800000ms during compilation

**Comment by Hor911** [comment]
There is a problem with local file listing (ticket to YQ team https://nda.ya.ru/t/Zv0mAya47ALMz2 - YQ-3967)

As workaround disablr runtime lising with pragma

```
pragma s3.UseRuntimeListing="false";
```
