### ISSUE TITLE
OptimizerHints: allow underscore in table names

### ISSUE THREAD

**Issue by Hor911** [ydb-platform/ydb#12749]
```
pragma ydb.OptimizerHints = 
'
    JoinType(inventory catalog_sales Shuffle) 
';
```

Bad "OptimizerHints" setting for "$all" cluster: (yexception) yql/essentials/core/cbo/cbo_hints.cpp:137: Optimizer hints parser error at [line:1, pos:30], msg: Expected [)], but got [_]

Underscore `_` must be valid symbol in table name

**Comment by pashandor789** [comment]
https://github.com/ydb-platform/ydb/commit/7ce0ebfc94614baf62cb8130618d8eaf786696e5 - fixed
