### ISSUE TITLE
OptimizerHints: accept case insensitive keywords

### ISSUE THREAD

**Issue by Hor911** [ydb-platform/ydb#12750]
```
pragma ydb.OptimizerHints = 
'
    JoinType(catalogreturns catalogsales shuffle) 
';
```

Bad "OptimizerHints" setting for "$all" cluster: (yexception) yql/essentials/core/cbo/cbo_hints.cpp:137: Optimizer hints parser error at [line:1, pos:42], msg: Unknown JoinType: 'shuffle', supported algos: [Shuffle, Lookup, Broadcast]

**Comment by pashandor789** [comment]
fixed by https://github.com/ydb-platform/ydb/commit/7ce0ebfc94614baf62cb8130618d8eaf786696e5
