### ISSUE TITLE
Recover YDB Olap vs Clickhoust Perf regular run

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#12828]

**Comment by iddqdex** [comment]
Статус: запуски идут, вот дашборд с результатами: https://nda.ya.ru/t/4N6Ygq-j7AYq9i
Регулярные сообщения в [канал](https://t.me/+eUt9rf1I7iQwZDUy) сломались, чиню.

**Comment by iddqdex** [comment]
Отправка сообщений починена, все работает. Фикс тут: https://nda.ya.ru/t/ZQWyxNwT7AZ5Dd
