### ISSUE TITLE
Change Data Capture (CDC) support

### ISSUE THREAD

**Issue by xaka** [ydb-platform/ydb#13]
Does YDB support CDC or any other mechanism to stream data changes to Kafka, etc.?

**Comment by alexv-smirnov** [comment]
The feature is now available as part of the 22-4 stable release. Please visit https://ydb.tech/en/docs/concepts/cdc for details.

Events are written to a topic:
https://ydb.tech/en/docs/concepts/topic (concepts)
https://ydb.tech/en/docs/reference/ydb-cli/topic-overview (CLI)
https://ydb.tech/en/docs/reference/ydb-sdk/topic (Go SDK)
