### ISSUE TITLE
Implement uuid type in SDK and CLI

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#131]

**Comment by dcherednik** [comment]
UUID support for c++ sdk
https://github.com/ydb-platform/ydb/commit/7d2f2555b228e6d9eb05fb8d3e42f9bedd717bbe

CLI no need to change.

`
$ cat ~/q.sql 
declare $id as String;
$id='02d9fcea-1fba-11ed-861d-0242ac120002';

select cast($id as Uuid);
$ ./ydb -e <host> -d <db> table query execute -f ~/q.sql 
                                                                                                   
┌────────────────────────────────────────┐
 | column0                                                                                                                                    |
├────────────────────────────────────────┤
 | "02d9fcea-1fba-11ed-861d-0242ac120002"                                                                             |
└────────────────────────────────────────┘
`
