### ISSUE TITLE
YDB сервер не компилируется

### ISSUE THREAD

**Issue by TomskDiver** [ydb-platform/ydb#144]
Имеется Ubuntu 18.04

Т.к. докер (#142) и бинарник(#143) не работают, решил собрать сервер из исходников по инструкции https://github.com/ydb-platform/ydb/blob/main/BUILD.md в которой утверждается тестирование на Ubuntu 18.04

1 пункт прошёл нормально:
```
Hit:11 https://apt.llvm.org/bionic llvm-toolchain-bionic InRelease
Hit:17 https://apt.kitware.com/ubuntu bionic InRelease
```
2 пункт уже не работает:
```
# apt-get -y install git cmake python python3-pip ninja-build antlr3 m4 clang-12 lld-12 libidn11-dev libaio1 libaio-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package clang-12
E: Unable to locate package lld-12
```
Там уже в репах clang-16 и lld-16

**Comment by dcherednik** [comment]
Попробуйте добавить репозиторий
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-12 main
вместо
deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main

**Comment by TomskDiver** [comment]
@dcherednik спасибо! Замена репозитория помогла. Скомпилился бинарник и вроде даже запустился и работает.
