### ISSUE TITLE
add null datapoints at end&start of the range

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb#1515]
In order to ease chart display for chart component

Doing it on frontend will cause the issue with not selectable extreme points (on the chart above you can select only 561 MB points). So it should be done on backend with adjusting number of datapoints, relative to available range.

Also agreed not to convert `null` points to `0` on frontend, intervals, where data was not collected, should not be displayed (will be fixed here: https://github.com/ydb-platform/ydb-embedded-ui/issues/674)

**Comment by artemmufazalov** [comment]
endpoint: `viewer/json/render`

**Comment by artemmufazalov** [comment]
The fix should be done on backend in `viewer/json/render` endpoint
