### ISSUE TITLE
Add example for persistent queue implementation, as describe in the doc

### ISSUE THREAD

**Issue by julienfr112** [ydb-platform/ydb#24]
"including persistent queues" in the ReadMe

I don't see how to do that, not having things like "skip locked" in yql ?

**Comment by fomichev3000** [comment]
Thank you for the comment. We are going to solve some issues with persistent queues api and provide documentation.

**Comment by alexv-smirnov** [comment]
Persistent queues referenced in REAMDE were earlier available as part of a separate project. How they are included as "topics" to the core YDB open source build, stable 22-4. Please check the following links:
https://ydb.tech/en/docs/concepts/topic (concepts)
https://ydb.tech/en/docs/reference/ydb-cli/topic-overview (CLI)
https://ydb.tech/en/docs/reference/ydb-sdk/topic (Go SDK)
