### ISSUE TITLE
[pg] Segfault on select * from pg_type

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#2484]
Reproduce:
1. Run [local ydb ](https://github.com/ydb-platform/ydb/wiki/Local-run-postgres-tests#start-local-ydb)
2. `echo "select * from pg_type" | psql postgres://root:1234@localhost:5432/local`

[stacktrace](https://gist.githubusercontent.com/rekby/407483d3cf90624210c70e78f9c876b2/raw/99646a7518c2f29be2c188c5227cdc1a283f258d/gistfile1.txt)

**Comment by vitstn** [comment]
yqlrun behaviour: Fatal: ERROR:  invalid cache ID: 42

crash should be fixed in the ydbd itself

**Comment by vitstn** [comment]
https://github.com/ydb-platform/ydb/pull/2545

**Comment by vitstn** [comment]
should be fixed by https://github.com/ydb-platform/ydb/pull/2524
