### ISSUE TITLE
kubernetes create Storage errorinvalid type for tech.ydb.v1alpha1.Storage.spec.dataStore: got "map", expected "array", ValidationError(Storage.spec): missing required field "erasure" in tech.

### ISSUE THREAD

**Issue by huosenlin** [ydb-platform/ydb#25]
error: error validating "STDIN": error validating data: [ValidationError(Storage.spec.dataStore): invalid type for tech.ydb.v1alpha1.Storage.spec.dataStore: got "map", expected "array", ValidationError(Storage.spec): missing required field "erasure" in tech.ydb.v1alpha1.Storage.spec]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by sourcecd** [comment]
Hello!
Please send a full kuber spec

**Comment by mvgorbunov** [comment]
Try to use storage configs examples for [minicube](https://github.com/ydb-platform/ydb-kubernetes-operator/tree/master/samples/minikube) and [managed k8s](https://github.com/ydb-platform/ydb-kubernetes-operator/blob/master/samples).
