### ISSUE TITLE
[QueryService] ResultSet doesn't have columns if request doesn't return rows

### ISSUE THREAD

**Issue by alex268** [ydb-platform/ydb#2532]
For example
query1 `{ syntax: SYNTAX_YQL_V1 text: "SELECT id, name FROM query_service_test ORDER BY id;" }`
query2 `{ syntax: SYNTAX_YQL_V1 text: "SELECT id, name FROM query_service_test WHERE false ORDER BY id;" }`

first returns  `SUCCESS result_set { columns { name: "id" type { type_id: INT32 } } columns { name: "name" type { optional_type { item { type_id: UTF8 } } } } rows { ... } tx_meta { }`
second returns  `SUCCESS result_set { } tx_meta { }`

**Comment by alex268** [comment]
@spuchin @dcherednik, could you see this issue?

**Comment by dcherednik** [comment]
https://github.com/ydb-platform/ydb/pull/2897
