### ISSUE TITLE
This program was compiled for SSE42 which is not supported on your system

### ISSUE THREAD

**Issue by jxwdsb** [ydb-platform/ydb#26]
ydbd: This program was compiled for SSE42 which is not supported on your system, exiting...: Success
Errors found when starting storage process, cancelling start script

Docker can't run either

**Comment by zinal** [comment]
Adding the comment for completeness: YDB requires CPUs having AVX2 (as specified in the [documentation](https://ydb.tech/en/docs/cluster/system-requirements)).
SSE4.2 predates AVX2, so all chips having AVX2 include SSE4.2 as well.
YDB depends on SSE4.2, too.
