### ISSUE TITLE
Ошибки при запуске в Docker

### ISSUE THREAD

**Issue by wormen** [ydb-platform/ydb#27]
база запускалась согласно рекомендациям из раздела
https://ydb.tech/ru/docs/getting_started/self_hosted/ydb_docker

при запуске получаю вот такие ошибки

![image](https://user-images.githubusercontent.com/8462339/164881402-85578069-af3a-448d-8fa3-a34c4752be61.png)
![image](https://user-images.githubusercontent.com/8462339/164881479-6d404901-3f65-4ae1-8787-8fbc569ace12.png)

**Comment by gridnevvvit** [comment]
Есть ли какая-то информация о окружении? Если контейнер запускается на M1, то в таком окружении поддерживается только в режиме YDB_USE_IN_MEMORY_PDISKS=true https://ydb.tech/ru/docs/getting_started/self_hosted/ydb_docker#start-pars

**Comment by wormen** [comment]
> Есть ли какая-то информация о окружении? Если контейнер запускается на M1, то в таком окружении поддерживается только в режиме YDB_USE_IN_MEMORY_PDISKS=true https://ydb.tech/ru/docs/getting_started/self_hosted/ydb_docker#start-pars

какая информация помимо ОС интересует?

ОС ubuntu 20.04
оборудование серверное

**Comment by gridnevvvit** [comment]
Процессор? Падение под SIGILL намекает. Работает ли контейнер в режиме в памяти YDB_USE_IN_MEMORY_PDISKS=true ?

**Comment by wormen** [comment]
с параметром  YDB_USE_IN_MEMORY_PDISKS=true ошибка та же, но 
что с этой переменной, что без нее контейнер при этом не падает

информация о процессоре
![image](https://user-images.githubusercontent.com/8462339/164970378-e5e228e8-2ef0-4eea-8833-b9ea5ad52799.png)

**Comment by mvgorbunov** [comment]
Hi!
Looks like your CPU (Intel Xeon E5530) does not support AVX extenstions, which is necessary for YDB
 https://en.wikipedia.org/wiki/Advanced_Vector_Extensions

**Comment by wormen** [comment]
@mvgorbunov в документации ничего не указано, что процессор должен поддерживать инструкцию AVX, следовательно должно работать

но по факту да, в этом процессоре нет поддержки данной инструкции

**Comment by mvgorbunov** [comment]
Мы добавим аппаратные требования в документацию, спасибо!

**Comment by uh-zuh** [comment]
Было бы шикарно добавить явную проверку на это при старте и выводить понятное сообщение об ошибке, чего именно не хватает.

**Comment by zinal** [comment]
Системные требования были добавлены в документацию коммитом 831cae3e90b34598cb55c0465207ed086bd292a2
