### ISSUE TITLE
Support UUID columns for CDC

### ISSUE THREAD

**Issue by SammyVimes** [ydb-platform/ydb#2822]
The same as #2757

cdc: https://github.com/ydb-platform/ydb/blob/main/ydb/core/tx/datashard/change_record_cdc_serializer.cpp#L119

async replication: https://github.com/ydb-platform/ydb/blob/main/ydb/core/io_formats/cell_maker/cell_maker.cpp#L311

**Comment by antonkovalenko** [comment]
epic: #74

**Comment by va-kuznecov** [comment]
PR - https://github.com/ydb-platform/ydb/pull/3229
