### ISSUE TITLE
[healthcheck] ya ydb mon healthcheck always returns EMERGENCY status on big clusters

### ISSUE THREAD

**Issue by shmel1k** [ydb-platform/ydb#2882]

**Comment by AlexanderShprot** [comment]
https://github.com/ydb-platform/ydb/blob/b82e31c9e154e428418deee4a6c07364307b2071/ydb/core/health_check/health_check.cpp#L1991

**Comment by AlexanderShprot** [comment]
Хотим заскриптовать утилиту ydb monitoring healthcheck, чтобы она регулярно заходила на кластер и в случае действительно серьезных проблем сообщала нам об этом в специальный экстренный чат (или запускала звонок дежурному). Сейчас в этом есть определенные неудобства: при запуске утилиты на относительно большом кластере мы почти всегда получаем самый критичный статус EMERGENCY, хотя кластер абсолютно жив. Вот например из текущего вывода утилиты:
```
"self_check_result": "EMERGENCY",
...
"status": "RED",
"message": "Database has compute issues",
...
"status": "RED",
"message": "Compute is overloaded",
...
"status": "RED",
"message": "Pool usage over 99%",
```
Кажется, что это должны быть ORANGE сообщения и статус кластера должен быть MAINTENANCE_REQUIRED, т.к. это не значит что кластер умирает. Хочется реализовать здесь другую логику. Пока нам видится два варианта решения:
1. Понизить цвет некоторых сообщений на один градиент. Чтобы они были не RED, а ORANGE. Возможно, стоит рассмотреть вариант добавить в будущем фильтр на количество ORAGE сообщений, чтобы утилита могла сказать ALMOST_DEAD.
2. Либо ввести новый глобальный статус DEAD - чтобы мы завязались на него
