### ISSUE TITLE
Return explicit error on not completed PDisk restart

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb#2941]
When request to restart PDisk is sent, it returns HTML of Developer UI PDisk page, even if PDisk cannot be restarted

JSON with restart status message is expected here (probably some message, explaining, why BSC didn't restart PDisk)

Request data:
URL: `http://host:31002/node/1/actors/pdisks/pdisk000001002`
Method: `POST`
Content-Type: `application/x-www-form-urlencoded; charset=UTF-8`
Data: `restartPDisk=`

Do not return HTML on POST request method

**Comment by StekPerepolnen** [comment]
@artemmufazalov 
hi! you can use this for pdisk restart
```
curl -i -X POST 'https://proxy.ydb.nemax.nebiuscloud.net/man0-0024.ydb-dev.nemax.nebiuscloud.net:8765/tablets/app?TabletID=72057594037932033&exec=1' \
-H 'Content-Type: application/json' \
-d '{
  "Command": {
    "RestartPDisk": {
      "TargetPDiskId": {
        "NodeId": 1,
        "PDiskId": 1000
      }
    }
  }
}'
```
it's a POST request, it could only reply with Protobuf-text format
examples:
`Status { Success: true } Success: true ConfigTxSeqNo: 1324 `
- it's all good
`Status { Success: true } ErrorDescription: "GroupId# 2181038080 ExpectedStatus# DISINTEGRATED" `
- too many disks were restarted

**Comment by StekPerepolnen** [comment]
@artemmufazalov 
you could also use format as before. It returns json and doesn't contain consts in the url
```
curl 'https://proxy.ydb.nemax.nebiuscloud.net/man0-0024.ydb-dev.nemax.nebiuscloud.net:8765/node/1/actors/pdisks/pdisk000001001' \
    -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
    -H 'Cookie: _ym_uid=1707744089222164620; _ym_d=1709631000; yc_session=c1.9euamseVjJKNnZzKkJbIzY6cm5COz-3rmprHlYySjZ2cypGSyImRlJeVz83l8_dTI3NN-e8LI0V__t3z9xNScE357wsjRX_-1eL17Iac0ZCeiouX0YabndKJlpqImo3t-ZCPmpGWm83X9dudzMjNyJrJndLNz5zN0svPz8bSx5qayNKdnZ7Km8_KzpzMyZ7v_sXrmprHlYySjZ2cypiSypeejI_LlJQ.qeR90n8PrM9unjk_awq5C-HYClUwLhDOsKaOQjlyv53mGsn5_Pp5xgDW-8PVqnwf6abSMNXQ0kQCO7AFdjoVBQ' \
    --data-raw 'restartPDisk=' \
    --insecure
```
