### ISSUE TITLE
[pg] Handle BAD_SESSION status

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#2963]
Run on ydb-local https://github.com/ydb-platform/ydb/wiki/Local-run-postgres-tests

```
echo "asd; SELECT 1" | psql postgres://root:1234@localhost:5432/local
```

Result:
```
Status: INTERNAL_ERROR
Issues:
<main>: Error: Error while parsing query.
    <main>:1:2: Error: ERROR:  syntax error at or near "asd"


Status: BAD_SESSION
Issues:
<main>: Error: Session not found: ydb://session/3?node_id=1&id=NTg3ODA5ZDItYWJiMTcwODEtOWFmYzNkNDAtZTVjM2U2YjI=
```

Expected behaviour: Close TCP connection after INTERNAL_ERROR (better) or BAD_SESSION (acceptable) - as signal for client for reconnect.

Reason:
Now client library can't continue to work and will always receive error for died session, but can't know about it because connection alive.

**Comment by adameat** [comment]
could you please fill in some details? it's not clear to me

**Comment by rekby** [comment]
Duplicate of  to https://github.com/ydb-platform/ydb/issues/2898
