### ISSUE TITLE
feat: rows and size limits for part size in ExecuteQueryRequest

### ISSUE THREAD

**Issue by asmyasnikov** [ydb-platform/ydb#3087]
https://github.com/ydb-platform/ydb/blob/main/ydb/public/api/protos/ydb_query.proto#L154

**Comment by dcherednik** [comment]
limit in bytes has been added
https://github.com/ydb-platform/ydb/pull/3609/files

https://github.com/ydb-platform/ydb/pull/3609
https://github.com/ydb-platform/ydb/pull/3471

**Comment by dcherednik** [comment]
rows limit will be implement here https://github.com/ydb-platform/ydb/issues/3630
