### ISSUE TITLE
YDB CLI workload kv clean command fails with error

### ISSUE THREAD

**Issue by Gazizonoki** [ydb-platform/ydb#3205]

**Comment by kunga** [comment]
At first I got
```
kungasc@kungasc-dev:~/ydb/ydb/apps/ydb$ ydb -e <endpoint> -d /Root/myslice-db1 workload kv clean
/Root/myslice-db1//Root/myslice-db1/kv_test
Status: SCHEME_ERROR
Issues: 
<main>: Error: Path not found
```

Then I found that [here](https://github.com/ydb-platform/ydb/blob/e286a5d9ec909cf3112e4b4b64c0e59cf919e843/ydb/public/lib/ydb_cli/commands/ydb_workload.cpp#L489) we concatenate path and get `fullPath = /Root/myslice-db1//Root/myslice-db1/kv_test`

I tried to fix and removed the concatenation but got
```
/Root/myslice-db1/kv_test
Status: BAD_REQUEST
Issues: 
<main>: Fatal: ydb/core/grpc_services/rpc_calls.cpp:73: wrong path format 'kv_test', code: 1
```

Apparently the clean behaviour was broken [here](https://github.com/ydb-platform/ydb/commit/6c7989fb16150a749de292813114cdd38721b669#diff-33f37e3abb372ca57427c3796a4ca94d7f345bfe5aef17106ab73616e7a1b906L328) by @iddqdex 

I'm not sure how it was designed to work so I'd better leave it to you

**Comment by Gazizonoki** [comment]
I found problem: https://github.com/ydb-platform/ydb/commit/9c844450f920aeb6c7454bac7235469f95971290#diff-abacc3c1d4a5ade9d195f3391bfc2b5189e2549ccf06f127c863d2fa51d63de5R192

**Comment by Gazizonoki** [comment]
@kunga Fix merged
