### ISSUE TITLE
Type annotation error in case of full table path + VIEW 

### ISSUE THREAD

**Issue by dcherednik** [ydb-platform/ydb#3510]
SELECT /Root/SecondaryKeys.id
FROM table VIEW `test_index`

<main>: Error: Type annotation, code: 1030
    <main>:3:17: Error: At function: RemovePrefixMembers, At function: PersistableRepr, At function: SqlProject, At function: SqlProjectItem
        <main>:3:24: Error: At function: SqlAccess, At function: Member
            <main>:3:24: Error: Member not found: /Root/SecondaryKeys

**Comment by Tony-Romanov** [comment]
#4414

**Comment by va-kuznecov** [comment]
it needs to be merged into 24-1
