### ISSUE TITLE
ui create time bug

### ISSUE THREAD

**Issue by Zzzabiyaka** [ydb-platform/ydb#43]
![Screenshot from 2022-04-30 19-44-58](https://user-images.githubusercontent.com/79576401/166114670-d035b4fc-eafa-4e80-8bed-07852ed8f311.png)

**Comment by adameat** [comment]
it was fixed in ydb-platform/ydb-embedded-ui
https://github.com/ydb-platform/ydb-embedded-ui/commit/c9887dd162720667dcbe3b4834b3b0ba5a9f3f6e
