### ISSUE TITLE
PR broke ydb/tests/functional/clickbench/test.py.test_run_benchmark[generic-column]

### ISSUE THREAD

**Issue by Tony-Romanov** [ydb-platform/ydb#4358]
Вот этот PR ломает 4 YDB теста:
https://github.com/ydb-platform/ydb/pull/4096

В том числе и вот этот большой тест со множеством кейсов:
ydb/tests/functional/clickbench/test.py.test_run_benchmark[generic-column]

В двух тестах проблема была в выходном типе COUNT(*) и я это легко поправил.

Но в этом тесте проблема в типе Timestamp который в CS хранится как arrow::timestamp а YQL ожидает arrow::uint64.

Во-первых, это неправильно сознательно комитить то, что ломает работающие тесты. 

Во-вторых, решить это можно либо runtime преобразованием колонки, чего мы в CS очень  хотели избежать, либо просто убрав эту debug-only проверку, без которой всё работет. То есть по факту откатить это PR.

**Comment by spuchin** [comment]
@vitstn @iddqdex
