### ISSUE TITLE
YQL: Cross join results depends on input order

### ISSUE THREAD

**Issue by mxkovalev** [ydb-platform/ydb#4587]
The attached request has cross join over table and window function. Different input order leads to different result. Seems window function doesn't work correctly.

P.S. Roman asked to assign this ticket to you as the main professional in this sphere.

[test1_bad_sql.txt](https://github.com/ydb-platform/ydb/files/15332393/test1_bad_sql.txt)
[test2_good_sql.txt](https://github.com/ydb-platform/ydb/files/15332394/test2_good_sql.txt)
[trace_opt_1_bad.txt](https://github.com/ydb-platform/ydb/files/15332395/trace_opt_1_bad.txt)
[trace_opt_2_good.txt](https://github.com/ydb-platform/ydb/files/15332396/trace_opt_2_good.txt)

**Comment by Tony-Romanov** [comment]
According to SQL standard, if there is no ORDER BY, the database is free to return the rows in any order it thinks is most efficient.

**Comment by mxkovalev** [comment]
The question is not about order, Cross Join(a,b) returns 2 rows, Cross Join (b,a) return 30 rows. It looks incorrect.

**Comment by mxkovalev** [comment]
There is an issue with hang request (internal ticket is YQL-18858). That's why changes were reverted.
