### ISSUE TITLE
Flaky KqpQueryService.FlowControllOnHugeRealTable-LongRow

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#5206]
* https://nebius.testmo.net/automation/runs/results/30546?group_by=automation_run_tests:status_id&group_id=3&test_id=688278821

**Comment by CyberROFL** [comment]
https://nebius.testmo.net/automation/runs/results/31435?group_by=automation_run_tests:status_id&group_id=3&test_id=706405921

**Comment by dcherednik** [comment]
https://github.com/ydb-platform/ydb/pull/5470

**Comment by dcherednik** [comment]
Close for a while. Reopen or create new in case of fail
