### ISSUE TITLE
Flaky HiveMetastoreClient.SuccessTrinoRequest

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#5220]
* https://nebius.testmo.net/automation/runs/results/30602?group_by=automation_run_tests:status_id&group_id=3&test_id=689258936

**Comment by dorooleg** [comment]
https://github.com/ydb-platform/ydb/pull/5233

**Comment by dorooleg** [comment]
Замержил: https://github.com/ydb-platform/ydb/pull/5233
