### ISSUE TITLE
Flaky KqpOlapAggregations.Aggregation_ResultCountAll_FilterL

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#5230]
* https://nebius.testmo.net/automation/runs/results/30639?group_by=automation_run_tests:status_id&group_id=3&test_id=689618544

**Comment by CyberROFL** [comment]
https://nebius.testmo.net/automation/runs/results/32566?group_by=automation_run_tests:status_id&group_id=3&test_id=728929705

**Comment by CyberROFL** [comment]
muted: https://github.com/ydb-platform/ydb/pull/5713

**Comment by zverevgeny** [comment]
duplicate [#7299](https://github.com/ydb-platform/ydb/issues/7299)
