### ISSUE TITLE
[[YQL]] Adapt WideLastCombinerWrapper to work with spilling in LLVM

### ISSUE THREAD

**Issue by Darych** [ydb-platform/ydb#5416]
Currently, spilling in WideLastCombiner works just when LLVM is disabled.
It will be great to be able to use spilling in WideLastCombiner when LLVM is turned on.

**Comment by Tony-Romanov** [comment]
Get rid of using comp nodes inside state.
https://github.com/Tony-Romanov/ydb/blob/main/ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp#L352

**Comment by Tony-Romanov** [comment]
Another problem that I didn’t notice at first.
Please return back members instead of this methods:
https://github.com/ydb-platform/ydb/blob/main/ydb/library/yql/minikql/comp_nodes/mkql_wide_combine.cpp#L415-L442
