### ISSUE TITLE
TPC-DS q23 fails with OptUseFinalizeByKey

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#5475]
Дело в том, что в таблице store_sales в колонках ss_customer_sk и ss_sold_date_sk могут быть NULL. А они являются ключами джоина. В JoinDict в случае Inner join мы требуем, чтобы ключи джоина были не NULL.

**Comment by Tony-Romanov** [comment]
Где тест, или как это воспроизводить?

**Comment by zverevgeny** [comment]
@Darych, допиши сюда, пожалуйста, минимальный пример воспроизводящий ошибку

**Comment by Tony-Romanov** [comment]
Понятней не стало. Чем это воспроизводится? Можно в виде теста куда-то в github положить?

**Comment by Tony-Romanov** [comment]
Получилось запустить на dqrun и запрос успешно отработал.

**Comment by yumkam** [comment]
q23 или q23 с `FinalizeByKey`?
Только что проверил,
https://gist.github.com/yumkam/72a58da03d56b0ef21ab9d90155c4ff2
валится

**Comment by Tony-Romanov** [comment]
Взял это запрос и эти биндинги и всё отработло. Не понимаю что я не так делаю.

**Comment by Tony-Romanov** [comment]
И ещё не понятно откуда вообще может браться JoinDict?
После перехода на GraceJoin он уже не должен возникать вообще никогда.

**Comment by yumkam** [comment]
Можно сравнить логи, plan, ast и результат. Я добавил в gist.

**Comment by Tony-Romanov** [comment]
Там нечего сравнивать ибо JoinDict вообще не должен возникать никогда, даже если отработал правильно.
Надо подебажить оптимайзер и посмотреть почему он возник.
А gateways.cfg можно сюда положить?

**Comment by yumkam** [comment]
Почти не отличается от dqrun/examples/gateways.conf. Добавил в gist.

**Comment by yumkam** [comment]
А какие опции сборки у `dqrun`? Если `release`, то там отключены `assert`, и он просто проглатывает багу.
(В `relwithdebinfo`, не только отладочная информация, но и, внезапно, `assert` не отключены)
