### ISSUE TITLE
correct block channels behaviour in auto mode by default in YDB

### ISSUE THREAD

**Issue by gridnevvvit** [ydb-platform/ydb#5636]

**Comment by abyss7** [comment]
There is a couple of problems left from our side:

- [ ] Print correct column names in the query plan.
- [ ] Fix tests expecting the "Collect" stage name in the query plan.

**Comment by abyss7** [comment]
Should mention to not forget that the query plan with wide channels differs from narrow one - at least the "Filter" node is missing.
