### ISSUE TITLE
Test altering tiering rules

### ISSUE THREAD

**Issue by iddqdex** [ydb-platform/ydb#5668]
see also:
YDB-2372
YDB-2376

**Comment by zverevgeny** [comment]
что нужно не забыть:
- удаляются ли данные в s3 при удалении таблицы.
- Что происходит, если в S3 бакет пропал, 
- если доступа нет, 
- если клиент сам руками в этот бакет полезет что-то удалять\менять?

**Comment by swalrus1** [comment]
Реализованные сценарии:
- Смена правил тиринга параллельно с записью
- Параллельная смена правил тиринга у разных таблиц в одном store
- Удаление данных из S3 при удалении таблицы

**Comment by swalrus1** [comment]
При недоступности S3 bulk upsert выполняется, а скан-запросы, затрагивающие недоступные блобы, падают. После восстановления S3 скан-запросы снова выполняются. Этот сценарий сложно автоматизировать в тестах, поэтому я проверил вручную.

**Comment by swalrus1** [comment]
Найденные баги:
- https://github.com/ydb-platform/ydb/issues/8257
- https://github.com/ydb-platform/ydb/pull/8261
