### ISSUE TITLE
Flaky TPersQueueCommonTest.Auth_WriteUpdateTokenRequestWithInvalidToken_SessionClosedWithUnauthenticatedError

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#5691]
* https://nebius.testmo.net/automation/runs/results/32460?group_by=automation_run_tests:status_id&group_id=3&test_id=727715470

**Comment by qyryq** [comment]
Похоже, релевантных падений больше нет по этому тесту. Закрою ишью. Если снова всплывет, вернемся.
