### ISSUE TITLE
Broken SqlToYQLErrors.SelectingFromMonitoringIsNotAllowed

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#5692]
* https://nebius.testmo.net/automation/runs/results/32442?group_by=automation_run_tests:status_id&group_id=3&test_id=727484474

**Comment by CyberROFL** [comment]
https://github.com/ydb-platform/ydb/pull/5571

**Comment by uzhastik** [comment]
https://github.com/ydb-platform/ydb/pull/5618
