### ISSUE TITLE
Compare benchmarks on different storages

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#5770]
Run benchmarks 

**Clusters** (two clusters to distinguish hw and sw issues):
  - olap-perf-sas
  - olap-testing-sas-common

**Storage**:
 - CS
 - DS
 - S3

**Benchmarks**:
- Clickbench:
- TPC-H 10G(100G)
- TPC-DS 10G

**Comment by iddqdex** [comment]
Запущено, по первым результатам заведены тикеты:
https://github.com/ydb-platform/ydb/issues/5981
https://github.com/ydb-platform/ydb/issues/6283
https://github.com/ydb-platform/ydb/issues/6284
https://github.com/ydb-platform/ydb/issues/6320
https://github.com/ydb-platform/ydb/issues/6383
