### ISSUE TITLE
How to enforce ydbd to listen at all ip addresses?

### ISSUE THREAD

**Issue by oleg68** [ydb-platform/ydb#61]
When I start ydb with ``./start.sh disk`` according to https://cloud.yandex.com/en-ru/docs/ydb/getting_started/self_hosted/ydb_local, the database lis accessible ony from `localhost`:

```
[root@ydb ~]#  netstat -lnp |grep 2136
tcp6       0      0 127.0.0.1:2136          :::*                    LISTEN      11337/ydbd          
```
Is it possible to start with listening at all ips, ie `0.0.0.0:2136` instead of `127.0.0.1:2136`?

**Comment by mvgorbunov** [comment]
This script and documentation are about local YDB deployment.
Use [On-premise deployment](https://ydb.tech/en/docs/deploy/manual/deploy-ydb-on-premises) documentation for multinode cluster setup.

**Comment by aHsirG** [comment]
![image](https://user-images.githubusercontent.com/22575581/169986374-8315e162-c49d-4f2a-b85e-59cef69783c0.png)
@oleg68 you need remove grpc_config and monitoring_config in config.yaml
after remove port listing on 0.0.0.0
my answer is not official, but help me open port

**Comment by oleg68** [comment]
@aHsirG thank you very much. It works
