### ISSUE TITLE
Unable to build ydb with debug symbols

### ISSUE THREAD

**Issue by oleg68** [ydb-platform/ydb#62]
I can build ydb with successfully in several hours.

```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/oleg/work/ydb/Ydb/clang.toolchain /home/oleg/work/ydb/Ydb /home/oleg/work/ydb/Ydb
ninja
```

But when I change ``-DCMAKE_BUILD_TYPE=Release`` to ``-DCMAKE_BUILD_TYPE=Debug``, I receive an error at the linkinng stage:

cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=/home/oleg/work/ydb/Ydb/clang.toolchain /home/oleg/work/ydb/Ydb /home/oleg/work/ydb/Ydb
ninja
...
ld.lld: error: undefined symbol: NKikimr::NPDisk::YdbDefaultPDiskSequence
>>> referenced by node_warden.h:52 (/home/oleg/work/ydb/Ydb/ydb/core/blobstorage/nodewarden/node_warden.h:52)
>>>               node_warden_pdisk.cpp.o:(NKikimr::TNodeWardenConfig::CreatePDiskKey() const) in archive ydb/core/blobstorage/nodewarden/libcore-blobstorage-nodewarden.a

ld.lld: error: undefined symbol: NKikimr::CreateBlobStorageGroupProxyMockActor()
>>> referenced by node_warden_proxy.cpp:21 (/home/oleg/work/ydb/Ydb/ydb/core/blobstorage/nodewarden/node_warden_proxy.cpp:21)
>>>               node_warden_proxy.cpp.o:(NKikimr::NStorage::TNodeWarden::StartLocalProxy(unsigned int)) in archive ydb/core/blobstorage/nodewarden/libcore-blobstorage-nodewarden.a
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

The full listing is attached [linkerr.txt](https://github.com/ydb-platform/ydb/files/8764504/linkerr.txt)

**Comment by fomichev3000** [comment]
Thanks for reporting an issue. Internal ticket is YDBOPS-5338, hope to fix it.

**Comment by fomichev3000** [comment]
I've found that the issue is about tests only, you can build server binary using `ninja ydb/apps/ydbd/ydbd` as a workaround.
Still working on the problem (KIKIMR-14996).

**Comment by fomichev3000** [comment]
Fixed. Debug build also works for tests from now.
