### ISSUE TITLE
`viewer/storage` doesn't return groups and vdisks data when filtered by `node_id`

### ISSUE THREAD

**Issue by artemmufazalov** [ydb-platform/ydb#6475]
Request: `https://proxy/host:8765/viewer/json/storage?enums=true&node_id=1&with=all&sort=&version=v1` returns only pools data without groups and vdisks, pools are not filtered (all pools are returned)

**Comment by adameat** [comment]
can't reproduce on the current version
![image](https://github.com/user-attachments/assets/5abf6e26-7551-44f6-a436-673ed9f6b480)
