### ISSUE TITLE
[[s3 perf]]: make precharge work with ext-blobs

### ISSUE THREAD

**Issue by SammyVimes** [ydb-platform/ydb#6486]
External blobs are not being precharged if read with read iterator. 
Without precharging each external blob is requested separately. 
Measured speed up is 2 times.

**Comment by SammyVimes** [comment]
https://github.com/ydb-platform/ydb/pull/5758

**Comment by snaury** [comment]
Thankfully this hasn't been merged into stable branches yet, there may be a serious bug: #7769.
