### ISSUE TITLE
[pg/pgwire] Bad type assumptions at parametrized queries.

### ISSUE THREAD

**Issue by MrLolthe1st** [ydb-platform/ydb#6733]
Run DBeaver, open local -> schemes -> public -> tables
DBeaver sends Bind with one long: https://github.com/dbeaver/dbeaver/blob/530742d80358424b121392c7c09386dad7f09407/plugins/org.jkiss.dbeaver.ext.postgresql/src/org/jkiss/dbeaver/ext/postgresql/model/PostgreSchema.java#L838
But at our side we're assuming that parameter to be unknown, that isn't true. Error follows: invalid byte sequence for encoding UTF8: 0x00.

```
SELECT c.oid,c.*,d.description,pg_catalog.pg_get_expr(c.relpartbound, c.oid) as partition_expr,  pg_catalog.pg_get_partkeydef(c.oid) as partition_key 
FROM pg_catalog.pg_class c
LEFT OUTER JOIN pg_catalog.pg_description d ON d.objoid=c.oid AND d.objsubid=0 AND d.classoid='pg_class'::regclass
WHERE c.relnamespace=$1 AND c.relkind not in ('i','I','c')
```

**Comment by shnikd** [comment]
We can't fix it now, the parameter type is required
