### ISSUE TITLE
GetInfo(): requirement info failed.

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#6813]
Failed: <main>: Error: Internal error while compiling query.
    <main>: Error: ydb/core/kqp/query_data/kqp_prepared_query.cpp:219: GetInfo(): requirement info failed.

Падает на TPC-DS 1 q34, q73
https://proxy.sandbox.yandex-team.ru/6687163720/index.html#suites/efe4970bacd9e1454955dc0317c12f5e/e7be07b86c13ca65/

**Comment by pavelvelikhov** [comment]
Cannot reproduce after recent fixes
