### ISSUE TITLE
Error: Delivery problem: EvScanDataAck lost

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#6829]
TPC-DS100 q14
Нужны логи

**Comment by zverevgeny** [comment]
repro https://proxy.sandbox.yandex-team.ru/6789224252/index.html#suites/1640a4c9e146c013eda93e0e2fa6bb4b/cdc02135a550984b/

TPC-DS10 Q72

**Comment by gridnevvvit** [comment]
Sep 19 15:44:11 ydb-vla-testing-0014 kikimr_31003[1381459]: 2024-09-19T12:44:11.889183Z :TX_COLUMNSHARD_SCAN ERROR: Scan [50007:7416331563836148998:7957] guard execution timeout txId: 281475038525657 scanId: 7 gen: 1 tablet: 72075186224041043
Sep 19 15:44:11 ydb-vla-testing-0014 kikimr_31003[1381459]: 2024-09-19T12:44:11.889192Z :TX_COLUMNSHARD_SCAN DEBUG: Scan [50007:7416331563836148998:7957] finished for tablet 72075186224041043

**Comment by gridnevvvit** [comment]
при этом он слал данные буквально секунду назад 

Sep 19 15:44:10 ydb-vla-testing-0014 kikimr_31003[1381459]: 2024-09-19T12:44:10.040896Z :TX_COLUMNSHARD_SCAN DEBUG: SelfId=[50007:7416331563836148998:7957];TabletId=72075186224041043;ScanId=7;TxId=281475038525657;ScanGen=1;method=produce result;fline=plain_read_data.cpp:73;event=DoExtractReadyResults;result=0;count=0;finished=0;
Sep 19 15:44:10 ydb-vla-testing-0014 kikimr_31003[1381459]: 2024-09-19T12:44:10.040898Z :TX_COLUMNSHARD_SCAN DEBUG: SelfId=[50007:7416331563836148998:7957];TabletId=72075186224041043;ScanId=7;TxId=281475038525657;ScanGen=1;method=produce result;fline=actor.cpp:197;stage=limit exhausted;limit=limits:(bytes=0;chunks=0);;
