### ISSUE TITLE
Failed to build physical query: some stages are broken

### ISSUE THREAD

**Issue by zverevgeny** [ydb-platform/ydb#6830]
Failed: <main>: Error: Execution, code: 1060
    <main>:26:1: Error: Failed to build physical query: some stages are broken

https://proxy.sandbox.yandex-team.ru/6702038226/index.html#suites/9f2f1bee336a2125852e724942907211/c548d8ce66baf99/
Tpcds100.Query39

**Comment by pavelvelikhov** [comment]
https://github.com/ydb-platform/ydb/pull/7308
