### ISSUE TITLE
Query 64 in TCPDS on scale 1000 fails with Type annotation error

### ISSUE THREAD

**Issue by pavelvelikhov** [ydb-platform/ydb#6986]
Running the query results in an error:

   <main>:177:1: Warning: At function: RemovePrefixMembers, At function: Sort, At function: PersistableRepr, At function: SqlProject
        <main>:219:19: Warning: At function: Filter, At function: EquiJoin, At function: RemoveSystemMembers
            <main>:25:3: Warning: At function: PersistableRepr, At function: SqlProject
                <main>:63:25: Warning: At function: AssumeColumnOrderPartial, At function: Aggregate, At function: Filter, At function: Coalesce
                    <main>:141:50: Warning: At function: And, At function: And, At function: And, At function: And, At function: And
                        <main>:137:10: Warning: At function: SqlIn
                            <main>:137:10: Warning: IN may produce unexpected result when used with nullable arguments. Consider adding 'PRAGMA AnsiInForEmptyOrNullableItemsCollections;', code: 1108
<main>: Error: Execution, code: 1060
    <main>:177:1: Error: At tuple, At tuple, At tuple, At function: TopSort, At function: FlatMap, At function: OptionalIf
        <main>:227:14: Error: At function: <=, At function: <=, At function: <=
            <main>:227:14: Error: Uncompatible types in compare: Optional<String> '<=' Uint64

My preliminary analysis is that member indexing is broken in GraceSelfJoinCore, resulting in wrong members being compared.

The query can be reproduced by uncommenting it in kqp_join_order_ut.cpp unit tests

**Comment by zverevgeny** [comment]
fixed
