### ISSUE TITLE
Query TPCDS 87 fails on scale 1000

### ISSUE THREAD

**Issue by pavelvelikhov** [ydb-platform/ydb#6988]
AST приложен

И вот такая там проблема:

Прблема вот тут:
(let $97 (DqCnHashShuffle (TDqOutput $59 '0) $53))
(let $98 (DqCnMap (TDqOutput $96 '0)))
(let $99 (Uint64 '1))
(let $100 (DqPhyStage '($97 $98) (lambda '($256 $257) (block '(
...

У нас у стадии два входа: DqCnHashShuffle и DqCnMap. Это невалидный план, мы не можем сделать с одной стороны шафл, а с другой мап. Надо понять как так вообще получилось.

Воспроизвести можно в UT в kqp_join_order_ut.cpp в этом PR: https://github.com/ydb-platform/ydb/pull/6982
[tpcds87_ast.txt](https://github.com/user-attachments/files/16348181/tpcds87_ast.txt)

**Comment by zverevgeny** [comment]
fixed
