### ISSUE TITLE
[pg] Segfault by incorrect query to pg_tables

### ISSUE THREAD

**Issue by rekby** [ydb-platform/ydb#7287]
Reproduce:

1. https://github.com/ydb-platform/ydb/wiki/Local-run-postgres-tests

2. Create any table by separate query:

```
echo "drop table t; create table t(id serial primary key);" | psql postgres://root:1234@localhost:5432/local
```

3. Execute right after that (in few seconds):
```
echo "select tablename from pg_tables where hasindexes='pg_proc';" | psql postgres://root:1234@localhost:5432/local
```

It may be some race: the problem doesn't reproduce if starts ydb with exists table or when I wait few minutes before execute incorrect query.

**Comment by rekby** [comment]
may be like https://github.com/ydb-platform/ydb/issues/7286

**Comment by qrort** [comment]
does not reproduce after https://github.com/ydb-platform/ydb/commit/633ff575647118017b3e38bfc7e58d1fb350cf34 is merged

**Comment by qrort** [comment]
Segfault has a corrupted backtrace, and the only frame of it i can see is `longjmp`. It hints that some exception, namely, `{ <main>: Error: ydb/library/yql/minikql/computation/mkql_value_builder.cpp:52: Terminate was called, reason(57): ERROR:  invalid input syntax for type boolean: "pg_proc" }` is not handled correctly.

pg_tables implementation gives out correct CellVec, and it is successfully passed to execution. [Here](https://github.com/ydb-platform/ydb/blob/1c9d9af1e671f4cabceeefcc18c522ba5a555683/ydb/library/yql/parser/pg_wrapper/postgresql/src/backend/utils/adt/bool.c#L151) it throws an exception, and I am unable to go through the line with gdb as it hangs indefinetely.

I tried to replicate the pattern with something like this:
```
echo "drop table t; create table t(id boolean primary key, value boolean);" | psql postgres://root:1234@localhost:5432/local
echo "insert into t values (true, true)" | psql postgresql://root:1234@localhost:5432/local
echo "SELECT value from t where value='pg_proc';" | psql postgresql://root:1234@localhost:5432/local
```

if i spam only the last query, no segfault occurs. But if i do it like this:

```
echo "drop table t; create table t(id boolean primary key, value boolean);" | psql postgres://root:1234@localhost:5432/local
echo "insert into t values (true, true)" | psql postgresql://root:1234@localhost:5432/local
echo "select tablename from pg_tables where hasindexes='pg_proc';" | psql postgres://root:1234@localhost:5432/local
echo "SELECT value from t where value='pg_proc';" | psql postgresql://root:1234@localhost:5432/local
```

the last query fails. it is seen in the [logs](https://gist.github.com/qrort/b0a00d7567fbe1ae725c204cd8abace1) that pg_tables query terminates successfully, while the next causes an error.

I'm not sure what causes the behaviour. Maybe the fact that CellVec is created w\o `TScopedAlloc` (see [here](https://github.com/ydb-platform/ydb/blob/main/ydb/core/sys_view/pg_tables/pg_tables.cpp#L25))plays a role, but I do not really know.
