### ISSUE TITLE
passing quotes and slashed in variables ya.make

### ISSUE THREAD

**Issue by OrlovPavel** [ydb-platform/ydb#7638]
I have a [PR](https://github.com/ydb-platform/ydb/pull/2977). It is about migrating yql grammar to antlr4 parser and I have some issue with ya.make file. I want to set the following variable:
```cmake
SET(GRAMMAR_STRING_CORE_DOUBLE "\"~([\"\\\\]) | (BACKSLASH .)\"")
```
Actually, I want the following value to occur in the generated file.:
```
~(["\\]) | (BACKSLASH .)
```
But I didn't manage to correctly pass a double quote and a backslash to the Python script in `build/scripts/configure_file.py`. So, how can I do it in Ya Make?

**Comment by asmyasnikov** [comment]
Fixed in 8fbad371206713c1a4e15a89dc2b43d99e0e64c9
