### ISSUE TITLE
List all supported predicates in documentation

### ISSUE THREAD

**Issue by OSA413** [ydb-platform/ydb#82]
I want to check if a value starts with some substring, I tried to search it in the `WHERE` section but with no luck.
https://ydb.tech/en/docs/yql/reference/syntax/select#where

**Comment by PatriotRossii** [comment]
That's listed in `Built-in functions` section: [StartsWith, EndsWith](https://ydb.tech/en/docs/yql/reference/builtins/basic#starts_ends_with)

**Comment by spuchin** [comment]
> > I want to check if a value starts with some substring, I tried to search it in the `WHERE` section but with no luck. https://ydb.tech/en/docs/yql/reference/syntax/select#where
> 
> That's listed in Built-in functions section: [StartsWith, EndsWith](https://ydb.tech/en/docs/yql/reference/builtins/basic#starts_ends_with)

Built-in functions section of documentation is a right place to look for such things:
https://ydb.tech/en/docs/yql/reference/builtins/basic

`WHERE` clause accepts arbitrary expressions, so everything returning `bool` (or `bool?`) is supported.
