### ISSUE TITLE
Errors on CS scheme operations via query service

### ISSUE THREAD

**Issue by ildar-khisambeev** [ydb-platform/ydb#8526]
Any scheme operation, which I try to execute in YDB monitoring embedded UI with Query type = "YQL - QueryService (default)", fails.
Example:
Query: CREATE TABLE ... WITH (STORE = COLUMN)
Error: Scheme operations cannot be executed inside transaction

Tried on cluster OLAP Perf VLA 1 with YDB version main.93089ee

**Comment by spuchin** [comment]
We should use NoTx (do not specify TxControl) for QueryService when working from UI. It will execute query in implicit transaction, which allows scheme operations.
@adameat

**Comment by adameat** [comment]
what is the version of YDB server?

**Comment by mvgorbunov** [comment]
@adameat is this issue still relevant?

**Comment by adameat** [comment]
> @adameat is this issue still relevant?

I don't think it is
