### ISSUE TITLE
[feature] JDBC driver

### ISSUE THREAD

**Issue by WatchTh1** [ydb-platform/ydb#9]
Well, that's what is wanted, would like to get the point when, where and how to get the thing ?
Хотелось бы понять, есть ли, планируется, когда и как ждать?

**Comment by Aracturat** [comment]
You can try this https://github.com/yandex-cloud/ydb-java-sdk/tree/master/jdbc

**Comment by fomichev3000** [comment]
We have to move jdbc repository to github.com/ydb-platform @alex268

**Comment by alex268** [comment]
JDBC Driver is available here https://github.com/ydb-platform/ydb-jdbc-driver
