### ISSUE TITLE
Утечка памяти в BulkUpsert

### ISSUE THREAD

**Issue by iddqdex** [ydb-platform/ydb#9408]
Как воспроизвести:
```bash
# Заводим ROW таблички в базе
ydb workload tpch -p tpch/s0 init --clear

# Заполняем их
ydb workload tpch -p tpch/s0 import generator --scale 10000
```
Во время заполнения память, потребляемая ydb-cli непрерывно растет пока не придет омм.
Если закомментировать [строчку в коде](https://github.com/ydb-platform/ydb/blob/7873f896651363cfabd1e56d0a8e1dca10b0b727/ydb/public/lib/ydb_cli/commands/ydb_workload_import.cpp#L86), то проблема уйдет.

Санитайзер показывает, что память остается в строках, передаваемых в BulkUpsert в качестве данных.

**Comment by pnv1** [comment]
Заметил, что во время заполнения первой таблички, customers, потребление дорастает до 10гб, а потом плавно снижается. Доходит до 3гб и на второй табличке уже доходит до 20гб и упирается в лимит (у меня на ВМ 24гб).
Потом заметил, что пока растет память, приложение усиленно потребляет CPU.
Попробовал снизить инфлайт BulkUpsert'ов со 128 до 1: приложение так же быстро выжирало память и потребляло много CPU. Как только доходило до 10гб на первой табличке, потребление памяти начинало медленно снижаться, а потребление CPU сразу падало почти в 0.
Стало очевидно, что генерилка данных генерила все данные для текущей таблички наперёд и не учитывала скорость отправки на сервер.
Почти сразу стало понятно, что этот цикл ничего не ждет и запрашивает все данные у генератора https://github.com/ydb-platform/ydb/blob/main/ydb/public/lib/ydb_cli/commands/ydb_workload_import.cpp#L101
Т.к. семафор асинхронный, процесс никто не "придерживает". Пофиксили заменой на обычный семафор:
https://github.com/ydb-platform/ydb/pull/9601
