### ISSUE TITLE
tpcds q9 unexpected memory limit exception on query

### ISSUE THREAD

**Issue by gridnevvvit** [ydb-platform/ydb#9621]
> Iteration 2: <main>: Error: Mkql memory limit exceeded, allocated by task 181: 7984906240, host: d-c0fb0me5j664knpup24h-ydb-testing-vla-0-4, canAllocateExtraMemory: 1, memory manager details for current node: TxResourcesInfo { TxId: 844425020611971, Database: /olap-testing-vla-perf/kikimr/olap/benchmark, PoolId: default, MemoryPoolPercent: 100.00, tx initially granted memory: 9MiB, tx total memory allocations: 29.8GiB, tx largest successful memory allocation: 56MiB, tx largest failed memory allocation: 8MiB, tx total execution units: 9, started at: 2024-09-20T22:34:19.043982Z }, code: 2029

it's seems like there is no reason for this query to run out of memory here.

**Comment by gridnevvvit** [comment]
on scale 10 this query is also quite slow

**Comment by pavelvelikhov** [comment]
https://github.com/ydb-platform/ydb/pull/11426
