### ISSUE TITLE
Release node name on graceful shutdown

### ISSUE THREAD

**Issue by CyberROFL** [ydb-platform/ydb#9734]
Node should release its custom name (if used) on graceful shutdown, allowing it to be used immediately for another node.

**Comment by NeimadTL** [comment]
@CyberROFL , @pixcc, it seems like the name release should be done [here](https://github.com/ydb-platform/ydb/blob/main/ydb/core/mind/node_broker__register_node.cpp#L111)  correct ? If so, is it as easy as setting the node's name attribute to `null` or are there any consideration to take into account ? Also, where is the node object defined please ?

**Comment by pixcc** [comment]
@NeimadTL

In fact, there's already a pull-request [here](https://github.com/ydb-platform/ydb/pull/10367#pullrequestreview-2411229277), with almost all the necessary changes. But its author hasn't made any updates for quite a long time. I'll try to ask him if he's still interested in it.


> it seems like the name release should be done [here](https://github.com/ydb-platform/ydb/blob/main/ydb/core/mind/node_broker__register_node.cpp#L111) correct ?

Almost, this is the process of releasing the name if the node is re-registered as serving different database. In this context subdomain, tenant and database are synonyms. The node name is formed from the prefix `slot-` and the sequence number of the node within the database (this number is called `SlotIndex` in this code). So if a node has started serving another database, it must release the slot index it occupied within the previous database, and acquire the slot index within the new database.

You can read more about this feature in [docs](https://ydb.tech/docs/en/reference/configuration/#node-broker-config).

>  If so, is it as easy as setting the node's name attribute to null or are there any consideration to take into account ?

It's actually a little more complicated than just setting the name attribute to `null`. It requires a new message that the compute node is going to send to the Node Broker during its graceful shutdown to release the node name. Upon receiving this message, the Node Broker will release the node name in the in-memory data structures (`SlotIndexPools`) and in [the persistent local database](https://ydb.tech/docs/en/concepts/glossary#local-database). These changes will also require a feature flag, [there are examples in code](https://github.com/ydb-platform/ydb/blob/872bb4d25b2454e82c5bbc045690c97cb64846ab/ydb/core/protos/feature_flags.proto#L11). You can estimate

> Also, where is the node object defined please ?

It is defined [here](https://github.com/ydb-platform/ydb/blob/872bb4d25b2454e82c5bbc045690c97cb64846ab/ydb/core/mind/node_broker_impl.h#L93).

**Comment by pixcc** [comment]
@NeimadTL

I reached the author of the pull request. He said he's interested in finishing this pull-request, there's really not much left, he's almost done.

But there are many other issues that are suitable for newcomers as well. I can help you find a task that interests you in the field of the Node Broker or database backups.

**Comment by NeimadTL** [comment]
Hey @pixcc,  thanks you so much for the information you've provided, I've got some reading to do !

Thanks for sharing the PR already for this. It's nice to have it so that can (try to) understand it.

Regarding the other issues to work on, how about this [one](https://github.com/ydb-platform/ydb/issues/9733) ? Otherwise feel free to mention me and/or assign me on one you feel that fits best. Thanks
